networks:
  custom_network:
    external: true

services:
  maltego-trx:
    image: maltego-trx:gunicorn
    container_name: maltego-trx
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - custom_network